/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        
        surface: '#fcf9f4',
        'surface-dim': '#dcdad5',
        'surface-bright': '#fcf9f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ee',
        'surface-container': '#f0ede9',
        'surface-container-high': '#ebe8e3',
        'surface-container-highest': '#e5e2dd',
        'surface-variant': '#e5e2dd',
        'surface-tint': '#45664e',
        
        'on-surface': '#1c1c19',
        'on-surface-variant': '#424842',
        'inverse-surface': '#31302d',
        'inverse-on-surface': '#f3f0eb',
        
        outline: '#727972',
        'outline-variant': '#c2c8c0',
        
        primary: '#32533c',
        'on-primary': '#ffffff',
        'primary-container': '#4a6b53',
        'on-primary-container': '#c5eacc',
        'inverse-primary': '#abcfb2',
        'primary-fixed': '#c7ecce',
        'primary-fixed-dim': '#abcfb2',
        'on-primary-fixed': '#01210f',
        'on-primary-fixed-variant': '#2e4e37',
        
        secondary: '#99462a',
        'on-secondary': '#ffffff',
        'secondary-container': '#fe9572',
        'on-secondary-container': '#762c12',
        'secondary-fixed': '#ffdbd0',
        'secondary-fixed-dim': '#ffb59e',
        'on-secondary-fixed': '#390b00',
        'on-secondary-fixed-variant': '#7a2f15',
        
        tertiary: '#793921',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#975037',
        'on-tertiary-container': '#ffd9cc',
        'tertiary-fixed': '#ffdbcf',
        'tertiary-fixed-dim': '#ffb59c',
        'on-tertiary-fixed': '#390c00',
        'on-tertiary-fixed-variant': '#73341d',
        
        background: '#fcf9f4',
        'on-background': '#1c1c19',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        gutter: '1.5rem',
        'gutter-sm': '1rem',
        margin: '2rem',
        'margin-mobile': '1rem',
      },
      fontFamily: {
        'display-hero': ['var(--font-noto-serif)', 'Noto Serif', 'serif'],
        'headline-lg': ['var(--font-noto-serif)', 'Noto Serif', 'serif'],
        'headline-md': ['var(--font-noto-serif)', 'Noto Serif', 'serif'],
        'headline-sm': ['var(--font-noto-serif)', 'Noto Serif', 'serif'],
        'body-reading': ['var(--font-noto-serif)', 'Noto Serif', 'serif'],
        'body-quote': ['var(--font-noto-serif)', 'Noto Serif', 'serif'],
        'title-md': ['var(--font-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'title-sm': ['var(--font-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['var(--font-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['var(--font-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['var(--font-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['var(--font-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
